version: '2.4'

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

volumes:
  mysql: {}

networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"

services:
  nginx:
    container_name: "${CTX_NAME}-main-nginx"
    hostname: "nginx"
    build:
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: $NGINX_IMAGE
        VERSION: $NGINX_VERSION
        PERL_VERSION: $PERL_VERSION
        MAIN_DOMAIN: $MAIN_DOMAIN
        MAIN_DOMAIN_PORT: $MAIN_DOMAIN_PORT
        MAIN_DOMAIN_PORT_SUFFIX: $MAIN_DOMAIN_PORT_SUFFIX
        PMA_DOMAIN: $PMA_DOMAIN
        PMA_DOMAIN_PORT: $PMA_DOMAIN_PORT
        PMA_DOMAIN_PORT_SUFFIX: $PMA_DOMAIN_PORT_SUFFIX
    restart: "unless-stopped"
    depends_on:
    - "mediawiki"
    - "phpmyadmin"
    ports:
    - "$NGINX_HTTP_PORT:80"
    - "$NGINX_HTTPS_PORT:443"
    - "$NGINX_PRIVATE_HTTP_PORT:9080"
    - "$NGINX_PRIVATE_HTTPS_PORT:9443"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_NGINX

  mediawiki:
    container_name: "${CTX_NAME}-main-mediawiki"
    hostname: "mediawiki"
    build:
      context: .
      dockerfile: "main/mediawiki/Dockerfile"
      args:
        IMAGE: $MEDIAWIKI_IMAGE
        VERSION: $MEDIAWIKI_VERSION
    restart: "unless-stopped"
    depends_on:
    - "mysql"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/mediawiki/uploads:/var/www/html/images"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_MEDIAWIKI

  phpmyadmin:
    container_name: "${CTX_NAME}-main-phpmyadmin"
    hostname: "phpmyadmin"
    build:
      context: .
      dockerfile: "main/phpmyadmin/Dockerfile"
      args:
        IMAGE: $PMA_IMAGE
        VERSION: $PMA_VERSION
        PERL_VERSION: $PERL_VERSION
        LOGIN_COOKIE_VALIDITY: $PMA_LOGIN_COOKIE_VALIDITY
    restart: "unless-stopped"
    environment:
      PMA_HOST: $DB_HOST
      PMA_PORT: $DB_PORT
    depends_on:
    - "mysql"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/tmp/phpmyadmin:/tmp/main/phpmyadmin"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_PMA

  mysql:
    container_name: "${CTX_NAME}-main-mysql"
    hostname: "mysql"
    build:
      context: .
      dockerfile: "main/mysql/Dockerfile"
      args:
        IMAGE: $MYSQL_IMAGE
        VERSION: $MYSQL_VERSION
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_ROOT_PASSWORD"
      MYSQL_DATABASE: "$DB_NAME"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"
    networks:
    - "shared"
    volumes:
    - "mysql:/var/lib/mysql"
    - "$DATA_DIR/tmp/mysql:/tmp/main/mysql"
    mem_limit: $CONTAINER_MEM_MYSQL

  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build:
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX