version: "2.4"

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"

services:
  mysql_cli:
    container_name: "${CTX_NAME}-main-mysql_cli"
    hostname: "mysql_cli"
    build:
      context: .
      dockerfile: "main/mysql/Dockerfile"
      args:
        IMAGE: $MYSQL_IMAGE
        VERSION: $MYSQL_VERSION
    networks:
    - "shared"
    extra_hosts:
    - "mysql:$DB_HOST_IP"
    volumes:
    - "$DATA_DIR/tmp/mysql:/tmp/main/mysql"
    mem_limit: $CONTAINER_MEM_MYSQL

  s3_backup:
    container_name: "${CTX_NAME}-run-s3_backup"
    hostname: "s3_backup"
    build:
      context: .
      dockerfile: "main/awscli/Dockerfile"
      args:
        IMAGE: $AWSCLI_IMAGE
        VERSION: $AWSCLI_VERSION
        PERL_VERSION: $PERL_VERSION
        S3_ACCESS_KEY: $S3_BACKUP_ACCESS_KEY
        S3_SECRET_KEY: $S3_BACKUP_SECRET_KEY
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_S3_BACKUP
