version: '2.4'

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options: 
      max-size: "50m"

volumes:
  mysql: {}

networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"

services:
  nginx:
    container_name: "${CTX_NAME}-main-nginx"
    hostname: "nginx"
    build: 
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: $NGINX_IMAGE
        VERSION: $NGINX_VERSION
        PERL_VERSION: $PERL_VERSION
        MAIN_DOMAIN: $MAIN_DOMAIN
        MAIN_DOMAIN_PORT: $MAIN_DOMAIN_PORT
        MAIN_DOMAIN_PORT_SUFFIX: $MAIN_DOMAIN_PORT_SUFFIX
    restart: "unless-stopped"
    depends_on:
    - "mediawiki"
    ports:
    - "$NGINX_HTTP_PORT:80"
    - "$NGINX_HTTPS_PORT:443"
    networks:
    - "shared"
    volumes: 
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_NGINX

  mediawiki:
    image: mediawiki:1.34.1
    container_name: "${CTX_NAME}-main-mediawiki"
    hostname: "mediawiki"
    build: 
      context: .
      dockerfile: "main/mediawiki/Dockerfile"
      args:
        IMAGE: $MEDIAWIKI_IMAGE
        VERSION: $MEDIAWIKI_VERSION
    restart: "unless-stopped"
    depends_on:
    - "mysql"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/mediawiki/images:/var/www/html/images"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_MEDIAWIKI

  mysql:
    container_name: "${CTX_NAME}-main-mysql"
    hostname: "mysql"
    build: 
      context: .
      dockerfile: "main/mysql/Dockerfile"
      args:
        IMAGE: $MYSQL_IMAGE
        VERSION: $MYSQL_VERSION
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
    - "shared"
    volumes: 
    - "mysql:/var/lib/mysql"
    - "$DATA_DIR/tmp/mysql:/tmp/main/mysql"
    mem_limit: $CONTAINER_MEM_MYSQL

  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build: 
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes: 
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX