## general vars - start ###

{% set var_local = params.local | default(false) | bool %}
{% set var_pod_type = params.type | default('') %}

{% if not (var_pod_type in ['app']) %}
  {% set error = {} %}
  {{ error['error.pod_type.invalid.' + var_pod_type] }}
{% endif %}

{% set var_pod_kind = 'prometheus' %}

{% set var_main_base_dir = params.custom_dir %}
{% set var_main_dir = var_main_base_dir + '/' + var_pod_kind %}
{% set var_main_base_dir_container = (var_local and (params.custom_dir_sync | default(false) | bool))
  | ternary(var_main_base_dir + '-sync', var_main_base_dir)
%}
{% set var_main_dir_container = var_main_base_dir_container + '/' + var_pod_kind %}
{% set var_shared_dir = 'shared' %}

{% set var_data_dir = input.data_dir %}

{% set var_custom_ssl_main_domain = params.custom_ssl.main_domain | default('') %}
{% set var_custom_ssl_fullchain = params.custom_ssl.fullchain | default('') %}
{% set var_custom_ssl_privkey = params.custom_ssl.privkey | default('') %}
{% set var_use_custom_ssl = (var_custom_ssl_main_domain != '')
  and (var_custom_ssl_fullchain != '')
  and (var_custom_ssl_privkey != '')
%}

{% set var_prometheus_domain_port = params.custom_domain.prometheus_ssl | bool |
  ternary(params.custom_domain.private_https_port, params.custom_domain.private_http_port)
%}

{% set var_grafana_domain_port = params.custom_domain.grafana_ssl | bool |
  ternary(params.custom_domain.private_https_port, params.custom_domain.private_http_port)
%}

{% if params.use_theia | bool %}
  {% set var_theia_domain_port = params.custom_domain.theia_ssl | bool |
    ternary(params.custom_domain.private_https_port, params.custom_domain.private_http_port)
  %}
{% endif %}

{% if params.use_minio_gateway | bool %}
  {% set var_minio_gateway_domain_port = params.custom_domain.minio_gateway_ssl | bool |
    ternary(params.custom_domain.private_https_port, params.custom_domain.private_http_port)
  %}
{% endif %}

{% if params.use_filestash | bool %}
  {% set var_filestash_domain_port = params.custom_domain.filestash_ssl | bool |
    ternary(params.custom_domain.private_https_port, params.custom_domain.private_http_port)
  %}
{% endif %}

### main ###

env_files:

- when: false

{% if var_pod_type in ['app', 'web'] %}

{% if var_use_custom_ssl | bool %}

- src: "{{ var_custom_ssl_fullchain }}"
  dest: "env/nginx/ssl/live/{{ var_custom_ssl_main_domain }}/fullchain.pem"

- src: "{{ var_custom_ssl_privkey }}"
  dest: "env/nginx/ssl/live/{{ var_custom_ssl_main_domain }}/privkey.pem"

{% endif %}

- src: "{{ params.auth_file }}"
  dest: "env/nginx/conf/.htpasswd"

{% endif %}

templates:

{% set var_ctx_full_name = input.identifier %}
{% set var_use_prefix = params.use_pod_prefix | default(params.use_pod_full_prefix | default(false, true), true) | bool %}
{% set var_pod_prefix = params.use_pod_full_prefix | default(false) | ternary(var_ctx_full_name, input.pod_name) %}
{% set var_ctx_prefix_main = var_use_prefix | bool | ternary(var_pod_prefix + '-main-', '') %}
{% set var_ctx_prefix_run = var_use_prefix | bool | ternary(var_pod_prefix + '-run-', '') %}

- src: "{{ var_main_dir }}/templates/docker-compose.tpl.yml"
  dest: "docker-compose.yml"
  params:
    local: "{{ var_local | default(false) | bool | ternary('true', 'false') }}"
    main_dir: "{{ var_main_dir_container }}"
    pod_type: "{{ var_pod_type }}"
    named_volumes: "{{ params.named_volumes | default(false) }}"
    use_fluentd: "{{ params.use_fluentd }}"

    {% if params.use_fluentd | bool %}

    fluentd_port: "{{ params.custom_args.fluentd.port }}"

    {% set var_fluentd_output_plugin = params.custom_args.fluentd.output_plugin
      | default(
        (var_pod_type in ['app']) | ternary('file', 'elasticsearch')
      )
    %}

    fluentd_output_plugin: "{{ var_fluentd_output_plugin }}"

    {% if var_fluentd_output_plugin == 'elasticsearch' %}

    elasticsearch_host_ip: "{{ input.dependencies.elasticsearch.host }}"

    {% endif %}

    {% endif %}

    images: {{ params.custom_images | to_json }}
    memory: {{ params.custom_memory | to_json }}
    use_node_exporter: "{{ params.use_node_exporter }}"
    use_cadvisor: "{{ params.use_cadvisor }}"

    {% if var_pod_type in ['app', 'web'] %}

    use_nginx: "{{ params.use_nginx }}"
    use_theia: "{{ params.use_theia }}"
    use_minio_gateway: "{{ params.use_minio_gateway }}"
    use_filestash: "{{ params.use_filestash }}"
    use_custom_ssl: "{{ var_use_custom_ssl }}"
    use_certbot: "{{ params.use_certbot }}"

    {% endif %}

- src: "{{ var_main_dir }}/templates/docker-compose.tpl.run.yml"
  dest: "docker-compose.run.yml"
  params:
    local: "{{ var_local | default(false) | bool | ternary('true', 'false') }}"
    main_dir: "{{ var_main_dir_container }}"
    pod_type: "{{ var_pod_type }}"
    use_fluentd: "{{ params.use_fluentd }}"
    s3_cli: "{{ params.s3_cli }}"
    images: {{ params.custom_images | to_json }}
    memory: {{ params.custom_memory | to_json }}

    {% if params.use_fluentd | bool %}

    fluentd_port: "{{ params.custom_args.fluentd.port }}"

    {% endif %}

    {% if var_pod_type in ['app', 'web'] %}

    use_certbot: "{{ params.use_certbot }}"

    {% endif %}

- src: "{{ var_main_dir }}/templates/docker-compose.env"
  dest: ".env"
  params:
    ctx_full_name: "{{ var_ctx_full_name }}"
    ctx_prefix_main: "{{ var_ctx_prefix_main }}"
    ctx_prefix_run: "{{ var_ctx_prefix_run }}"
    data_dir: "{{ var_data_dir }}"
    local: "{{ var_local | default(false) }}"
    type: "{{ var_pod_type }}"
    use_nginx: "{{ params.use_nginx }}"
    use_fluentd: "{{ params.use_fluentd }}"

    {% if var_pod_type in ['app', 'web'] %}

    {% if params.use_nginx | bool %}

    public_http_port: "{{ params.custom_domain.public_http_port }}"
    public_https_port: "{{ params.custom_domain.public_https_port }}"
    private_http_port: "{{ params.custom_domain.private_http_port }}"
    private_https_port: "{{ params.custom_domain.private_https_port }}"

    {% else %}

    grafana_port: "{{ params.custom_args.grafana.port }}"

    {% endif %}

    grafana_security_admin_password: "{{ credentials.grafana.security_admin_password }}"
    grafana_server_domain: "{{ credentials.grafana.server_domain }}"
    grafana_smtp_enabled: "{{ credentials.grafana.smtp_enabled }}"
    grafana_smtp_host: "{{ credentials.grafana.smtp_host }}"
    grafana_smtp_user: "{{ credentials.grafana.smtp_user }}"
    grafana_smtp_password: "{{ credentials.grafana.smtp_password }}"
    grafana_smtp_from_address: "{{ credentials.grafana.smtp_from_address }}"

    {% endif %}

    {% if var_pod_type in ['app', 'web'] %}

    use_certbot: "{{ params.use_certbot }}"
    use_minio_gateway: "{{ params.use_minio_gateway }}"

    {% if params.use_minio_gateway | bool %}

    minio_gateway_endpoint: "{{ credentials.minio_gateway.endpoint }}"
    minio_gateway_access_key: "{{ credentials.minio_gateway.access_key }}"
    minio_gateway_secret_key: "{{ credentials.minio_gateway.secret_key }}"

    {% endif %}

    {% endif %}

{% if var_pod_type in ['app', 'web'] %}

{% if not params.custom_args.nginx.custom | default(false) | bool %}

- src: "{{ var_main_dir }}/templates/nginx/nginx.conf"
  dest: "env/nginx/nginx.conf"
  params:
    conf: {{ params.custom_args.nginx.conf | default({}) | to_json }}
    enable_validate_origin: "{{ params.custom_args.nginx.enable_validate_origin }}"
    main_domain: "{{ params.custom_domain.main_domain }}"
    main_ssl: "{{ params.use_ssl | default(false) }}"
    prometheus_domain: "{{ params.custom_domain.prometheus_domain }}"
    prometheus_port: "{{ var_prometheus_domain_port }}"
    prometheus_ssl: "{{ params.custom_domain.prometheus_ssl }}"
    grafana_domain: "{{ params.custom_domain.grafana_domain }}"
    grafana_port: "{{ var_grafana_domain_port }}"
    grafana_ssl: "{{ params.custom_domain.grafana_ssl }}"
    use_theia: "{{ params.use_theia }}"

    {% if params.use_theia | bool %}

    theia_domain: "{{ params.custom_domain.theia_domain }}"
    theia_port: "{{ var_theia_domain_port }}"
    theia_ssl: "{{ params.custom_domain.theia_ssl }}"

    {% endif %}

    use_minio_gateway: "{{ params.use_minio_gateway }}"

    {% if params.use_minio_gateway | bool %}

    minio_gateway_domain: "{{ params.custom_domain.minio_gateway_domain }}"
    minio_gateway_port: "{{ var_minio_gateway_domain_port }}"
    minio_gateway_ssl: "{{ params.custom_domain.minio_gateway_ssl }}"

    {% endif %}

    use_filestash: "{{ params.use_filestash }}"

    {% if params.use_filestash | bool %}

    filestash_domain: "{{ params.custom_domain.filestash_domain }}"
    filestash_port: "{{ var_filestash_domain_port }}"
    filestash_ssl: "{{ params.custom_domain.filestash_ssl }}"

    {% endif %}

{% endif %}

{% endif %}

{% if params.s3_cli == 'awscli' %}
  {% set var_s3_config_src = var_shared_dir + '/templates/awscli/credentials.ini' %}
  {% set var_s3_config_dest = 'env/awscli/credentials.ini' %}
{% elif params.s3_cli == 'rclone' %}
  {% set var_s3_config_src = var_shared_dir + '/templates/rclone/rclone.conf' %}
  {% set var_s3_config_dest = 'env/rclone/rclone.conf' %}
{% elif params.s3_cli == 'mc' %}
  {% set var_s3_config_src = var_shared_dir + '/templates/mc/config.json.j2' %}
  {% set var_s3_config_dest = 'env/mc/config.json' %}
{% endif %}

- src: "{{ var_s3_config_src }}"
  dest: "{{ var_s3_config_dest }}"
  params:
    - alias: "backup"
      endpoint: "{{ credentials.backup_bucket.endpoint }}"
      region: "{{ credentials.backup_bucket.region | default('') }}"
      access_key: "{{ credentials.backup_bucket.access_key }}"
      secret_key: "{{ credentials.backup_bucket.secret_key }}"
    - alias: "backup_replica"
      endpoint: "{{ credentials.backup_replica_bucket.endpoint }}"
      region: "{{ credentials.backup_replica_bucket.region | default('') }}"
      access_key: "{{ credentials.backup_replica_bucket.access_key }}"
      secret_key: "{{ credentials.backup_replica_bucket.secret_key }}"
      when: "{{ (params.enable_backup_replica | bool) and (var_pod_type in ['app', 'web']) }}"

- src: "main/vars/vars.tpl.sh"
  dest: "vars.sh"
  params:
    var_load_script_path: "{{ var_main_dir }}/scripts/prometheus.vars.sh"

    var_load_general__ctx_full_name: "{{ var_ctx_full_name }}"
    var_load_general__main_base_dir: "{{ var_main_base_dir }}"
    var_load_general__main_base_dir_container: "{{ var_main_base_dir_container }}"
    var_load_general__backup_is_delete_old: "true"

    var_load_main__data_dir: "{{ input.data_dir }}"
    var_load_main__pod_type: "{{ var_pod_type }}"
    var_load_main__local: "{{ var_local | default('') | lower }}"

    var_load_shared__delete_old__days: "3"

    var_load_use__main_network: "true"
    var_load_use__logrotator: "true"
    var_load_use__nginx: "true"
    var_load_use__fluentd: "{{ params.use_fluentd | default('') | lower }}"
    var_load_use__theia: "{{ params.use_theia | default('') | lower }}"
    var_load_use__certbot: "{{ params.use_certbot | default('') | lower }}"
    var_load_use__ssl: "{{ params.use_ssl | default('') | lower }}"
    var_load_use__custom_ssl: "{{ var_use_custom_ssl | default('') | lower }}"

    # Enable Tasks

    var_load_enable__logs_backup: "{{ params.enable_logs_backup | default('') | lower }}"
    var_load_enable__sync_backup: "{{ params.enable_sync_backup | default('') | lower }}"

    var_load_enable__logs_setup: "{{ params.enable_logs_setup | default('') | lower }}"
    var_load_enable__sync_setup: "{{ params.enable_sync_setup | default('') | lower }}"

    # Tasks

    var_load__certbot__dev: "{{ params.certbot.dev | default('') | lower }}"
    var_load__certbot__domains: "{{ params.certbot.domains | default('') }}"
    var_load__certbot__email: "{{ params.certbot.email | default('') }}"
    var_load__certbot__force: "{{ params.certbot.force | default('') | lower }}"
    var_load__certbot__main_domain: "{{ params.certbot.main_domain | default('') }}"
    var_load__certbot__rsa_key_size: "{{ params.certbot.rsa_key_size | default('') }}"
    var_load__certbot__staging: "{{ params.certbot.staging | default('') | lower }}"

    var_load__logs_setup__restore_bucket_path_dir: "{{ params.logs_setup.restore_bucket_path_dir | default('') }}"
    var_load__logs_setup__verify_file_to_skip: "{{ params.logs_setup.verify_file_to_skip | default('') }}"
    var_load__logs_setup__recursive_mode: "{{ params.logs_setup.recursive_mode | default('') }}"
    var_load__logs_setup__recursive_mode_dir: "{{ params.logs_setup.recursive_mode_dir | default('') }}"
    var_load__logs_setup__recursive_mode_file: "{{ params.logs_setup.recursive_mode_file | default('') }}"

    var_load__s3_backup__bucket_name: "{{ params.backup_bucket_name | default('') }}"
    var_load__s3_backup__bucket_path: "{{ params.backup_bucket_path | default('') }}"
    var_load__s3_backup__cli: "{{ params.s3_cli | default('') }}"
    var_load__s3_backup__endpoint: "{{ credentials.backup_bucket.endpoint | default('') }}"

    var_load__sync_setup__restore_bucket_path_dir: "{{ params.sync_setup.restore_bucket_path_dir | default('') }}"
    var_load__sync_setup__verify_file_to_skip: "{{ params.sync_setup.verify_file_to_skip | default('') }}"
    var_load__sync_setup__recursive_mode: "{{ params.sync_setup.recursive_mode | default('') }}"
    var_load__sync_setup__recursive_mode_dir: "{{ params.sync_setup.recursive_mode_dir | default('') }}"
    var_load__sync_setup__recursive_mode_file: "{{ params.sync_setup.recursive_mode_file | default('') }}"
