version: '2.4'
x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"
networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"
volumes:
  elasticsearch: {}
services:
  nginx:
    container_name: "${CTX_PREFIX_MAIN}nginx"
    hostname: "nginx"
    build:
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: "nginx"
        VERSION: "1.14.2-alpine"
    restart: "unless-stopped"
    depends_on:
    - "kibana"
    ports:
    - "$PUBLIC_HTTP_PORT:80"
    - "$PUBLIC_HTTPS_PORT:443"
    - "$PRIVATE_HTTP_PORT:9080"
    - "$PRIVATE_HTTPS_PORT:9443"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/sync/certbot/etc:/etc/ssl:ro"
    - "$DATA_DIR/sync/certbot/www:/var/www/certbot:ro"
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: "512mb"
  kibana:
    container_name: "${CTX_PREFIX_MAIN}kibana"
    hostname: "kibana"
    build:
      context: .
      dockerfile: "main/kibana/Dockerfile"
      args:
        IMAGE: "docker.elastic.co/kibana/kibana"
        VERSION: "7.5.0"
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/tmp/kibana:/tmp/main/kibana"
    logging: *mainlog
    mem_limit: "512mb"
  elasticsearch:
    container_name: "${CTX_PREFIX_MAIN}elasticsearch"
    hostname: "elasticsearch"
    build:
      context: .
      dockerfile: "main/elasticsearch/Dockerfile"
      args:
        IMAGE: "docker.elastic.co/elasticsearch/elasticsearch"
        VERSION: "7.5.0"
    restart: "unless-stopped"
    environment:
      cluster.initial_master_nodes: elasticsearch
      ES_JAVA_OPTS: "$ELASTICSEARCH_JAVA_OPTS"
    ports:
    - "$ELASTICSEARCH_PORT:9200"
    networks:
    - "shared"
    volumes:
    - "elasticsearch:/usr/share/elasticsearch/data"
    - "$DATA_DIR/tmp/elasticsearch:/tmp/main/elasticsearch"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        hard: -1
        soft: -1
    logging: *mainlog
    mem_limit: "1gb"
  toolbox:
    container_name: "${CTX_PREFIX_MAIN}toolbox"
    hostname: "toolbox"
    build:
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: "lucasbasquerotto/image"
        VERSION: "toolbox-20200513"
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main/app"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: "512mb"