version: '2.4'

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

networks:
  shared:
    external: true
    name: "${CTX_NAME}-network"

volumes:
  mongo_db: {}
  mongo_dump: {}

services:
  nginx:
    container_name: "${CTX_NAME}-main-nginx"
    hostname: "nginx"
    build:
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: $NGINX_IMAGE
        VERSION: $NGINX_VERSION
        PERL_VERSION: $PERL_VERSION
        MAIN_DOMAIN: $MAIN_DOMAIN
        MAIN_DOMAIN_PORT: $MAIN_DOMAIN_PORT
        MAIN_DOMAIN_PORT_SUFFIX: $MAIN_DOMAIN_PORT_SUFFIX
        MONGO_EXPRESS_DOMAIN: $MONGO_EXPRESS_DOMAIN
        MONGO_EXPRESS_DOMAIN_PORT: $MONGO_EXPRESS_DOMAIN_PORT
        MONGO_EXPRESS_DOMAIN_PORT_SUFFIX: $MONGO_EXPRESS_DOMAIN_PORT_SUFFIX
    restart: "unless-stopped"
    depends_on:
    - "rocketchat"
    - "mongo-express"
    ports:
    - "$NGINX_HTTP_PORT:80"
    - "$NGINX_HTTPS_PORT:443"
    - "$NGINX_PRIVATE_HTTP_PORT:9080"
    - "$NGINX_PRIVATE_HTTPS_PORT:9443"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_NGINX

  rocketchat:
    container_name: "${CTX_NAME}-main-rocketchat"
    hostname: "rocketchat"
    build:
      context: .
      dockerfile: "main/rocketchat/Dockerfile"
      args:
        IMAGE: $ROCKETCHAT_IMAGE
        VERSION: $ROCKETCHAT_VERSION
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: "unless-stopped"
    environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://$DB_USER:$DB_PASSWORD@mongo:27017/$DB_NAME?authSource=admin
    - MONGO_OPLOG_URL=mongodb://oploguser:$DB_OPLOG_PASSWORD@mongo:27017/local?authSource=admin
    - MAIL_URL=smtp://smtp.email
    depends_on:
    - "mongo"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR/rocketchat/uploads:/app/uploads"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_ROCKETCHAT

  mongo-express:
    container_name: "${CTX_NAME}-main-mongo-express"
    hostname: "mongo-express"
    build:
      context: .
      dockerfile: "main/mongo-express/Dockerfile"
      args:
        IMAGE: $MONGO_EXPRESS_IMAGE
        VERSION: $MONGO_EXPRESS_VERSION
    restart: "unless-stopped"
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    # - ME_CONFIG_BASICAUTH_USERNAME=$DB_USER
    # - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASS
    # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    # - ME_CONFIG_MONGODB_AUTH_USERNAME=$DB_ROOT_USER
    # - ME_CONFIG_MONGODB_AUTH_PASSWORD=$DB_ROOT_PASS
    - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_ROOT_USER
    - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_ROOT_PASS
    networks:
    - "shared"
    mem_limit: $CONTAINER_MEM_MONGO_EXPRESS

  mongo:
    container_name: "${CTX_NAME}-main-mongo"
    hostname: "mongo"
    build:
      context: .
      dockerfile: "main/mongo/Dockerfile"
      args:
        IMAGE: $MONGO_IMAGE
        VERSION: $MONGO_VERSION
    restart: "unless-stopped"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USER
    - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASS
    networks:
    - "shared"
    volumes:
    - "mongo_db:/data/db"
    - "mongo_dump:/dump"
    command: mongod --auth --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    mem_limit: $CONTAINER_MEM_MONGO

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    container_name: "${CTX_NAME}-main-hubot"
    hostname: "hubot"
    build:
      context: .
      dockerfile: "main/$HUBOT_DIR/Dockerfile"
      args:
        IMAGE: $HUBOT_IMAGE
        VERSION: $HUBOT_VERSION
    restart: unless-stopped
    environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_ROOM=$HUBOT_ROOM
    - ROCKETCHAT_USER=$HUBOT_USER
    - ROCKETCHAT_PASSWORD=$HUBOT_PASSWORD
    - BOT_NAME=$HUBOT_BOT_NAME
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    networks:
    - "shared"
    depends_on:
    - rocketchat
    volumes:
    - "$DATA_DIR/hubot/scripts:/home/hubot/scripts"

  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build:
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks:
    - "shared"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX