version: "2.4"

networks:
  internet: 
    driver: "bridge"
  log: 
    driver: "bridge"
  local: 
    internal: true
    driver: "bridge"

x-logging:
  mainlog: &mainlog
    driver: "fluentd"
    options: 
      tag: "docker.{{.Name}}.{{.ID}}"
      fluentd-address: "localhost:$FLUENTD_PORT"  
  jsonlog: &jsonlog
    driver: "json-file"
    options: 
      max-size: "50m"

services:

  nginx:
    container_name: "${CTX_NAME}-main-nginx"
    hostname: "nginx"
    build: 
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: $NGINX_IMAGE
        VERSION: $NGINX_VERSION
        PERL_VERSION: $PERL_VERSION
        MAIN_DOMAIN: $MAIN_DOMAIN
        MAIN_DOMAIN_PORT: $MAIN_DOMAIN_PORT
        MAIN_DOMAIN_PORT_SUFFIX: $MAIN_DOMAIN_PORT_SUFFIX
        PMA_DOMAIN: $PMA_DOMAIN
        PMA_DOMAIN_PORT: $PMA_DOMAIN_PORT
        PMA_DOMAIN_PORT_SUFFIX: $PMA_DOMAIN_PORT_SUFFIX
    restart: "unless-stopped"
    depends_on:
    - "wordpress"
    - "phpmyadmin"
    - "fluentd"
    ports:
    - "$MAIN_DOMAIN_PORT:80"
    - "$PMA_DOMAIN_PORT:9080"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_NGINX
    
  wordpress:
    container_name: "${CTX_NAME}-main-wordpress"
    hostname: "wordpress"
    build: 
      context: .
      dockerfile: "main/wordpress/Dockerfile"
      args:
        IMAGE: $WORDPRESS_IMAGE
        VERSION: $WORDPRESS_VERSION
        WORDPRESS_INI_FILE_TYPE: $WORDPRESS_INI_FILE_TYPE
    restart: "unless-stopped"
    depends_on:
    - "fluentd"
    environment:
      DB_HOST: $DB_HOST:$DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR/wordpress/uploads:/var/www/html/web/app/uploads"
    - "$DATA_DIR/tmp/wordpress:/tmp/main/wordpress"
    extra_hosts:
    - "mysql:$MYSQL_HOST_IP"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_WORDPRESS
    
  phpmyadmin:
    container_name: "${CTX_NAME}-main-phpmyadmin"
    hostname: "phpmyadmin"
    build: 
      context: .
      dockerfile: "main/phpmyadmin/Dockerfile"
      args:
        IMAGE: $PMA_IMAGE
        VERSION: $PMA_VERSION
        PERL_VERSION: $PERL_VERSION
        LOGIN_COOKIE_VALIDITY: $PMA_LOGIN_COOKIE_VALIDITY
    restart: "unless-stopped"
    depends_on:
    - "fluentd"
    environment:
      PMA_HOST: $DB_HOST
      PMA_PORT: $DB_PORT
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR/tmp/phpmyadmin:/tmp/main/phpmyadmin"
    extra_hosts:
    - "mysql:$MYSQL_HOST_IP"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_PMA
    
  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build: 
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    depends_on:
    - "fluentd"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX
    
  fluentd:
    container_name: "${CTX_NAME}-main-fluentd"
    hostname: "fluentd"
    build: 
      context: .
      dockerfile: "main/fluentd/Dockerfile"
      args:
        IMAGE: $FLUENTD_IMAGE
        VERSION: $FLUENTD_VERSION
        OUTPUT_PLUGIN: $FLUENTD_OUTPUT_PLUGIN
    restart: "unless-stopped"
    ports:
    - "$FLUENTD_PORT:24224"
    - "$FLUENTD_PORT:24224/udp"
    networks:
    - "log"
    extra_hosts:
    - "elasticsearch:$ELASTICSEARCH_HOST_IP"
    volumes:
    - "$DATA_DIR/log/fluentd:/var/log/main/fluentd/"
    logging: *jsonlog
    mem_limit: $CONTAINER_MEM_FLUENTD
    