version: "2.4"

x-logging:
  mainlog: &mainlog
    driver: "fluentd"
    options:
      tag: "docker.{{.Name}}.{{.ID}}"
      fluentd-address: "localhost:$FLUENTD_PORT"
  jsonlog: &jsonlog
    driver: "json-file"
    options:
      max-size: "50m"

networks:
  internet:
    driver: "bridge"
  log:
    driver: "bridge"
  local:
    internal: true
    driver: "bridge"

services:

  mysql:
    container_name: "${CTX_NAME}-main-mysql"
    hostname: "mysql"
    build:
      context: .
      dockerfile: "main/mysql/Dockerfile"
      args:
        IMAGE: $MYSQL_IMAGE
        VERSION: $MYSQL_VERSION
    restart: "unless-stopped"
    depends_on:
    - "fluentd"
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
    ports:
    - "3306:3306"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR/mysql:/var/lib/mysql"
    - "$DATA_DIR/tmp/mysql:/tmp/main/mysql"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_MYSQL

  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build:
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    depends_on:
    - "fluentd"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    - "$DATA_DIR/sync:/var/sync/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX

  fluentd:
    container_name: "${CTX_NAME}-main-fluentd"
    hostname: "fluentd"
    build:
      context: .
      dockerfile: "main/fluentd/Dockerfile"
      args:
        IMAGE: $FLUENTD_IMAGE
        VERSION: $FLUENTD_VERSION
        OUTPUT_PLUGIN: $FLUENTD_OUTPUT_PLUGIN
    restart: "unless-stopped"
    ports:
    - "$FLUENTD_PORT:24224"
    - "$FLUENTD_PORT:24224/udp"
    networks:
    - "log"
    extra_hosts:
    - "elasticsearch:$ELASTICSEARCH_HOST_IP"
    volumes:
    - "$DATA_DIR/log/fluentd:/var/log/main/fluentd/"
    logging: *jsonlog
    mem_limit: $CONTAINER_MEM_FLUENTD
