version: "2.4"

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options: 
      max-size: "50m"

volumes:
  mysql: {}

networks:
  internet: 
    driver: "bridge"
  local: 
    internal: true
    driver: "bridge"

services:
  nginx:
    container_name: "${CTX_NAME}-main-nginx"
    hostname: "nginx"
    build: 
      context: .
      dockerfile: "main/nginx/Dockerfile"
      args:
        IMAGE: $NGINX_IMAGE
        VERSION: $NGINX_VERSION
        PERL_VERSION: $PERL_VERSION
        MAIN_DOMAIN: $MAIN_DOMAIN
        MAIN_DOMAIN_PORT: $MAIN_DOMAIN_PORT
        MAIN_DOMAIN_PORT_SUFFIX: $MAIN_DOMAIN_PORT_SUFFIX
        PMA_DOMAIN: $PMA_DOMAIN
        PMA_DOMAIN_PORT: $PMA_DOMAIN_PORT
        PMA_DOMAIN_PORT_SUFFIX: $PMA_DOMAIN_PORT_SUFFIX
    restart: "unless-stopped"
    depends_on:
    - "wordpress"
    - "phpmyadmin"
    ports:
    - "$MAIN_DOMAIN_PORT:80"
    - "$PMA_DOMAIN_PORT:9080"
    networks: 
    - "internet"
    - "local"
    volumes: 
    - "$DATA_DIR/tmp/nginx:/tmp/main/nginx"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_NGINX
    
  wordpress:
    container_name: "${CTX_NAME}-main-wordpress"
    hostname: "wordpress"
    build: 
      context: .
      dockerfile: "main/wordpress/Dockerfile"
      args:
        IMAGE: $WORDPRESS_IMAGE
        VERSION: $WORDPRESS_VERSION
        WORDPRESS_INI_FILE_TYPE: $WORDPRESS_INI_FILE_TYPE
    restart: "unless-stopped"
    environment:
      DB_HOST: $DB_HOST:$DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
    depends_on:
    - "mysql"
    networks: 
    - "internet"
    - "local"
    volumes: 
    - "$WP_APP_REPO_DIR:/var/www/html"
    - "$DATA_DIR/wordpress/uploads:/var/www/html/web/app/uploads"
    - "$DATA_DIR/tmp/wordpress:/tmp/main/wordpress"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_WORDPRESS
    
  phpmyadmin:
    container_name: "${CTX_NAME}-main-phpmyadmin"
    hostname: "phpmyadmin"
    build: 
      context: .
      dockerfile: "main/phpmyadmin/Dockerfile"
      args:
        IMAGE: $PMA_IMAGE
        VERSION: $PMA_VERSION
        PERL_VERSION: $PERL_VERSION
        LOGIN_COOKIE_VALIDITY: $PMA_LOGIN_COOKIE_VALIDITY
    restart: "unless-stopped"
    environment:
      PMA_HOST: $DB_HOST
      PMA_PORT: $DB_PORT
    depends_on:
    - "mysql"
    networks: 
    - "local"
    volumes: 
    - "$DATA_DIR/tmp/phpmyadmin:/tmp/main/phpmyadmin"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_PMA
    
  mysql:
    container_name: "${CTX_NAME}-main-mysql"
    hostname: "mysql"
    build: 
      context: .
      dockerfile: "main/mysql/Dockerfile"
      args:
        IMAGE: $MYSQL_IMAGE
        VERSION: $MYSQL_VERSION
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USER
    networks: 
    - "local"
    volumes: 
    - "mysql:/var/lib/mysql"
    - "$DATA_DIR/tmp/mysql:/tmp/main/mysql"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_MYSQL
    
  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build: 
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks: 
    - "internet"
    - "local"
    volumes: 
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX
    
  composer:
    container_name: "${CTX_NAME}-main-composer"
    hostname: "composer"
    build: 
      context: .
      dockerfile: "main/composer/Dockerfile"
      args:
        IMAGE: $COMPOSER_IMAGE
        VERSION: $COMPOSER_VERSION
    restart: "unless-stopped"
    volumes: 
    - "$WP_APP_REPO_DIR:/var/www/html"
    - "$DATA_DIR/tmp/composer:/tmp/main/composer"
    logging: *mainlog
    command: "tail -f /dev/null"
    working_dir: "/var/www/html"
    mem_limit: $CONTAINER_MEM_COMPOSER
    