root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      local:
        type: "bool"
        non_empty: true
      main_dir:
        type: "str"
        non_empty: true
      app_dev:
        type: "str"
        non_empty: true
      pod_type:
        type: "str"
        non_empty: true
        choices: ["app", "web", "cache", "db"]
      shared_network:
        type: "str"
        non_empty: true
      named_volumes:
        type: "str"
        non_empty: true
      internal:
        type: "bool"
        non_empty: true
      use_secrets:
        type: "bool"
        non_empty: true
      use_fluentd:
        type: "bool"
        non_empty: true
      use_internal_fluentd:
        type: "bool"
        non_empty: true
      use_s3:
        type: "bool"
        non_empty: true
      use_local_s3:
        type: "bool"
        non_empty: true
      use_nginx:
        type: "bool"
        non_empty: true
      use_varnish:
        type: "bool"
        non_empty: true
      use_pma:
        type: "bool"
        non_empty: true
      use_adminer:
        type: "bool"
        non_empty: true
      use_theia:
        type: "bool"
        non_empty: true
      use_minio_gateway:
        type: "bool"
        non_empty: true
      use_filestash:
        type: "bool"
        non_empty: true
      use_custom_ssl:
        type: "bool"
        non_empty: true
      use_internal_ssl:
        type: "bool"
        non_empty: true
      use_certbot:
        type: "bool"
        non_empty: true
      use_redis:
        type: "bool"
        non_empty: true
      use_memcached:
        type: "bool"
        non_empty: true
      use_composer:
        type: "bool"
        non_empty: true
      wordpress_ini_file_type:
        type: "str"
        non_empty: true
      db_host:
        type: "str"
        non_empty: true
      db_port:
        type: "str"
        non_empty: true
      db_name:
        type: "str"
        non_empty: true
      db_user:
        type: "str"
        non_empty: true
      db_gui_user:
        type: "str"
      fluentd_port:
        type: "str"
        non_empty: true
      fluentd_output_plugin:
        type: "str"
        non_empty: true
      elasticsearch_host:
        type: "str"
      s3_cli:
        type: "str"
        choices: ["", "awscli", "mc", "rclone"]
      ports:
        schema: "ports"
        non_empty: true
      images:
        type: "dict"
        required: true
      memory:
        type: "dict"
        required: true
  ports:
    type: "dict"
    props:
      public_http_port:
        type: "str"
        non_empty: true
      public_https_port:
        type: "str"
        non_empty: true
      private_http_port:
        type: "str"
        non_empty: true
      private_https_port:
        type: "str"
        non_empty: true
