root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      ctx_full_name:
        type: "str"
        non_empty: true
      ctx_prefix_main:
        type: "str"
        required: true
      ctx_prefix_run:
        type: "str"
        required: true
      type:
        type: "str"
        non_empty: true
        choices: ["app", "web", "cache", "db"]
      local:
        type: "bool"
        non_empty: true
      data_dir:
        type: "str"
        non_empty: true
      app_dev:
        type: "bool"
        non_empty: true
      wp_app_repo_dir:
        type: "str"
      use_secrets:
        type: "bool"
        non_empty: true
      use_minio_gateway:
        type: "bool"
        non_empty: true
      minio_gateway_endpoint:
        type: "str"
      minio_gateway_access_key:
        type: "str"
      minio_gateway_secret_key:
        type: "str"
      db_root_password:
        type: "str"
      db_gui_password:
        type: "str"
