root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      local:
        type: "bool"
        non_empty: true
      main_dir:
        type: "str"
        non_empty: true
      pod_type:
        type: "str"
        non_empty: true
        choices: ["app", "web", "cache", "db"]
      use_certbot:
        type: "bool"
      use_fluentd:
        type: "bool"
      fluentd_port:
        type: "str"
      s3_cli:
        type: "str"
        non_empty: true
        choices: ["awscli", "mc", "rclone"]
      images:
        type: "dict"
        required: true
      memory:
        type: "dict"
        required: true
