version: "2.4"

networks:
  internet: 
    driver: "bridge"
  local: 
    internal: true
    driver: "bridge"

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options: 
      max-size: "50m"

services:
    
  bind:
    container_name: "${CTX_NAME}-main-bind"
    hostname: "bind"
    build: 
      context: .
      dockerfile: "main/bind/Dockerfile"
      args:
        IMAGE: $BIND_IMAGE
        VERSION: $BIND_VERSION
        PERL_VERSION: $PERL_VERSION
        BIND_FILE: $BIND_FILE
        BIND_TYPE: $BIND_TYPE
        BIND_ZONE: $BIND_ZONE
        BIND_SECRET: $BIND_SECRET
        BIND_MASTER_IP: $BIND_MASTER_IP
        BIND_SLAVE_IP: $BIND_SLAVE_IP
        BIND_MASTER_NS: $BIND_MASTER_NS
        BIND_SLAVE_NS: $BIND_SLAVE_NS
        BIND_MASTER_COMMENT_NS: $BIND_MASTER_COMMENT_NS
        BIND_SLAVE_COMMENT_NS: $BIND_SLAVE_COMMENT_NS
        BIND_EMAIL_HOSTMASTER: $BIND_EMAIL_HOSTMASTER
        BIND_COMMENT_TRANSFER: $BIND_COMMENT_TRANSFER
        BIND_COMMENT_MASTERS: $BIND_COMMENT_MASTERS
        BIND_SERIAL: $BIND_SERIAL
    restart: "unless-stopped"
    networks:
    - "internet"
    - "local"
    ports:
    - "$BIND_PORT:53"
    - "$BIND_PORT:53/udp"
    volumes:
    - "$DATA_DIR/bind:/var/main/data/bind"
    - "$DATA_DIR/tmp/bind:/tmp/main/bind"
    - "$DATA_DIR/log/bind:/var/log/main/bind"
    logging: *mainlog
    mem_limit: $CONTAINER_MEM_BIND
    
  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build: 
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX
    