version: "2.4"

networks:
  internet: 
    driver: "bridge"
  local: 
    internal: true
    driver: "bridge"

x-logging:
  mainlog: &mainlog
    driver: "json-file"
    options: 
      max-size: "50m"

services:
    
  bind:
    container_name: "${CTX_NAME}-main-bind"
    hostname: "bind"
    build: 
      context: .
      dockerfile: "main/bind/Dockerfile"
      args:
        IMAGE: $BIND_IMAGE
        VERSION: $BIND_VERSION
        BIND_TYPE: $BIND_TYPE
    restart: "unless-stopped"
    networks:
    - "internet"
    - "local"
    ports:
    - "53:53"
    - "53:53/udp"
    volumes:
    - "$DATA_DIR/bind:/var/main/data/bind"
    - "$DATA_DIR/tmp/bind:/tmp/main/bind"
    - "$DATA_DIR/log/bind:/var/log/main/bind"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX
    
  toolbox:
    container_name: "${CTX_NAME}-main-toolbox"
    hostname: "toolbox"
    build: 
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    networks:
    - "internet"
    - "local"
    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX
    