{% set var_local = params.local | bool %}

{################################################################################################}
{% macro include_scripts() %}

    - "./main/scripts:/var/main/scripts/main/scripts:ro"
    - "./shared/scripts:/var/main/scripts/shared/scripts:ro"
    - "./{{ params.main_dir }}/scripts:/var/main/scripts/{{ params.main_dir }}/scripts:ro"

{% endmacro %}
{################################################################################################}

version: "2.4"

x-logging:

  {#############################################################}
  {% if params.use_fluentd | bool %}

  mainlog: &mainlog
    driver: "fluentd"
    options:
      tag: "{% raw %}docker.{{.Name}}{% endraw %}"
      fluentd-address: "localhost:{{ params.fluentd_port }}"
  jsonlog: &jsonlog
    driver: "json-file"
    options:
      max-size: "50m"

  {% else %}

  mainlog: &mainlog
    driver: "json-file"
    options:
      max-size: "50m"

  {% endif %}
  {#############################################################}

networks:
  shared:
    external: true
    name: "{{ params.shared_network }}"

services:

  {#############################################################}
  {% if params.pod_type in ['app', 'web'] %}

  {#############################################################}
  {% if params.use_certbot | bool %}

  certbot:
    container_name: "${CTX_PREFIX_RUN}certbot"
    hostname: "certbot"
    build:
      context: .
      dockerfile: "shared/containers/certbot/Dockerfile"
      args:
        IMAGE: "{{ params.images.certbot_image }}"
        VERSION: "{{ params.images.certbot_version }}"
    networks:
    - "shared"

    {#############################################################}
    {% if var_local %}

    extra_hosts:
      host.docker.internal: host-gateway

    {% endif %}
    {#############################################################}

    volumes:
    - "$DATA_DIR/sync/certbot/etc/:/etc/letsencrypt/"
    - "$DATA_DIR/sync/certbot/www/:/var/www/certbot/"

    {{ include_scripts() }}

    logging: *mainlog

    {#############################################################}
    {% if (params.memory.certbot | default('')) != '' %}

    mem_limit: "{{ params.memory.certbot }}"

    {% endif %}
    {#############################################################}

  {% endif %}
  {#############################################################}

  {% endif %}
  {#############################################################}

  {#############################################################}
  {% if params.pod_type in ['app', 'db'] %}

  mongo_init:
    container_name: "${CTX_PREFIX_RUN}mongo_init"
    hostname: "mongo_init"
    build:
      context: .
      dockerfile: "shared/containers/mongo/Dockerfile"
      args:
        IMAGE: "{{ params.images.mongo_image }}"
        VERSION: "{{ params.images.mongo_version }}"
    networks:
    - "shared"

    {#############################################################}
    {% if var_local %}

    extra_hosts:
      host.docker.internal: host-gateway

    {% endif %}
    {#############################################################}

    logging: *mainlog

    {#############################################################}
    {% if (params.memory.mongo_init | default('')) != '' %}

    mem_limit: "{{ params.memory.mongo_init }}"

    {% endif %}
    {#############################################################}

  {% endif %}
  {#############################################################}

  logrotator:
    container_name: "${CTX_PREFIX_RUN}logrotator"
    hostname: "logrotator"
    build:
      context: .
      dockerfile: "shared/containers/python3/Dockerfile"
      args:
        IMAGE: "{{ params.images.logrotator_image }}"
        VERSION: "{{ params.images.logrotator_version }}"
    restart: "unless-stopped"
    networks:
    - "shared"

    {#############################################################}
    {% if var_local %}

    extra_hosts:
      host.docker.internal: host-gateway

    {% endif %}
    {#############################################################}

    volumes:
    - "$DATA_DIR:/var/main/data"
    - "$DATA_DIR/tmp:/tmp/main"
    - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: python3 /bin/logrotate.py /tmp/main/log /var/log/main/rotated

    {#############################################################}
    {% if (params.memory.logrotator | default('')) != '' %}

    mem_limit: "{{ params.memory.logrotator }}"

    {% endif %}
    {#############################################################}
